#Symbol allowed for comment '#'
#key=value
#Symbol allwed to write keyName (dot(.), dash(-), underscore(_))
my.driver=oracle
my.url=oracle-jdbc
my.username=system
my.password=root
my.port=3306
my.active=fALSE