spring.application.name=BootConfigPropsEx-s22

my.app.host=GmailServer
my.app.port=586
my.app.username=IndiaFreeInternship
my.app.active=false

my.app.models[0]=M1
my.app.models[1]=M2
my.app.models[2]=M3
my.app.models[3]=M2

my.app.data.C1=ABC
my.app.data.C2=XYZ
my.app.data.C3=pqr

my.app.mob.code=C1325
my.app.mob.details=SampleMobile