# comment line
# symbol allowed to write keyName (dot . dash - underscore _)
#key=value
my.db=oracle
my.url=oracle-jdbc
my.username=indiafreeinternship
my.password=root
my.port=3306
#my.port=3345
#my.port=4444
my.enable=tRUe